name: Generate and Overwrite web.py Daily

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  generate-and-overwrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Pull remote changes
        run: git pull origin ${{ github.ref }}

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chromedriver-binary-auto selenium selenium-wire blinker==1.7.0

      - name: Run Python script to generate and overwrite web.py
        env:
          X_TOKEN: ${{ secrets.X_TOKEN }}
        run: python update_web_py.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add unofficial_twitter_client/web.py
          git diff-index --quiet HEAD || git commit -m "GitHub Actions: update web.py"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
          force: false
          pr_create: false
